kakao:
  client_id: ${client_id}
  redirect_uri: ${redirect_uri}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${url}
    username: ${username}
    password: ${password}
  thymeleaf:
    check-template-location: false
